Add OAuth2 support for authentication with Solace PubSub+ Broker
SolaceProducts/solace-spring-boot pull request #133
Opened 2024-07-12 18:35 UTC by mayur-solace

- Update the Spring Boot dependency to 3.3.1
- Update the Solace JCSMP dependency to 10.22.0
- Added Support for enabling OAuth2 authentication scheme with the Soalce PubSub+ Broker
- Added ITs for OAuth2 and Client Certificate authentication
- Updated the failsafe and surefire plugin version and updated existing unit test to JUnit5
- Added Sample for OAuth2 authentication
- Update the developer readme to include OAuth2 support
- Updated the version number in pom.xml file

2024-07-12 18:59 UTC, Nephery requested changes

2024-07-12 18:59 UTC, Nephery commented on .gitmodules
Since https://github.com/SolaceProducts/solace-spring-boot/pull/132 is merged in. You can merge `master` back into your branch, then you won't need this submodule anymore. You can also then remove all that stuff you added to the `pom.xml`

2024-07-12 19:58 UTC, mayur-solace commented on .gitmodules
Done.

2024-07-12 20:10 UTC, Nephery commented on pom.xml
> +                <!--<type>pom</type>-->
this should be uncommented.

2024-07-17 17:36 UTC, Nephery requested changes

2024-07-17 18:37 UTC, Nephery requested changes

2024-07-17 18:37 UTC, Nephery commented on solace-spring-boot-autoconfigure/solace-java-spring-boot-autoconfigure/src/main/java/com/solacesystems/jcsmp/DefaultSolaceSessionOAuth2TokenProvider.java
> +      DefaultSolaceSessionOAuth2TokenProvider.class);
use SLF4J instead of Apache Logging.

2024-07-17 18:37 UTC, Nephery commented on solace-spring-boot-autoconfigure/solace-java-spring-boot-autoconfigure/src/main/java/com/solacesystems/jcsmp/DefaultSolaceSessionOAuth2TokenProvider.java
> +        logger.debug("Exception while fetching OAuth2 access token: " + t);
once you switch to SLF4J, use `logger.debug("asdsadasd", t)` instead.

2024-07-18 15:26 UTC, merged